// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testORGS(t *testing.T) {
	t.Parallel()

	query := ORGS()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testORGSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testORGSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ORGS().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testORGSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ORGSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testORGSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ORGExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ORG exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ORGExists to return true, but got false.")
	}
}

func testORGSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	orgFound, err := FindORG(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if orgFound == nil {
		t.Error("want a record, got nil")
	}
}

func testORGSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ORGS().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testORGSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ORGS().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testORGSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	orgOne := &ORG{}
	orgTwo := &ORG{}
	if err = randomize.Struct(seed, orgOne, orgDBTypes, false, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}
	if err = randomize.Struct(seed, orgTwo, orgDBTypes, false, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orgOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orgTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ORGS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testORGSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	orgOne := &ORG{}
	orgTwo := &ORG{}
	if err = randomize.Struct(seed, orgOne, orgDBTypes, false, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}
	if err = randomize.Struct(seed, orgTwo, orgDBTypes, false, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = orgOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = orgTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func orgBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func orgAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ORG) error {
	*o = ORG{}
	return nil
}

func testORGSHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ORG{}
	o := &ORG{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, orgDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ORG object: %s", err)
	}

	AddORGHook(boil.BeforeInsertHook, orgBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	orgBeforeInsertHooks = []ORGHook{}

	AddORGHook(boil.AfterInsertHook, orgAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	orgAfterInsertHooks = []ORGHook{}

	AddORGHook(boil.AfterSelectHook, orgAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	orgAfterSelectHooks = []ORGHook{}

	AddORGHook(boil.BeforeUpdateHook, orgBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	orgBeforeUpdateHooks = []ORGHook{}

	AddORGHook(boil.AfterUpdateHook, orgAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	orgAfterUpdateHooks = []ORGHook{}

	AddORGHook(boil.BeforeDeleteHook, orgBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	orgBeforeDeleteHooks = []ORGHook{}

	AddORGHook(boil.AfterDeleteHook, orgAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	orgAfterDeleteHooks = []ORGHook{}

	AddORGHook(boil.BeforeUpsertHook, orgBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	orgBeforeUpsertHooks = []ORGHook{}

	AddORGHook(boil.AfterUpsertHook, orgAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	orgAfterUpsertHooks = []ORGHook{}
}

func testORGSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testORGSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(orgColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testORGSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testORGSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ORGSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testORGSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ORGS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	orgDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`, `Location`: `character varying`}
	_          = bytes.MinRead
)

func testORGSUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(orgPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(orgAllColumns) == len(orgPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orgDBTypes, true, orgPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testORGSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(orgAllColumns) == len(orgPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ORG{}
	if err = randomize.Struct(seed, o, orgDBTypes, true, orgColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, orgDBTypes, true, orgPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(orgAllColumns, orgPrimaryKeyColumns) {
		fields = orgAllColumns
	} else {
		fields = strmangle.SetComplement(
			orgAllColumns,
			orgPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ORGSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testORGSUpsert(t *testing.T) {
	t.Parallel()

	if len(orgAllColumns) == len(orgPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ORG{}
	if err = randomize.Struct(seed, &o, orgDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ORG: %s", err)
	}

	count, err := ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, orgDBTypes, false, orgPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ORG struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ORG: %s", err)
	}

	count, err = ORGS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
